# Global composer file for manage orchestration of front and back api in same build
# This file depends on three projects : Front-App, TuiFly.BookingApi and TuiFly.FlySearchApi

services:
  tuifly_app:
    build:
      context: ./src/Front-App
    environment:
      NODE_ENV: production
    ports:
      - 5088:3000

  tuifly_booking_api:
    build:
      context: ./src/Back-App/TuiFly.BookingApi
    ports:
      - 7022:80

  tuifly_flysearch_api:
    build:
      context: ./src/Back-App/TuiFly.FlySearchApi
    ports:
      - 7025:80